apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: feathr
data:
  discovery.type: single-node
  cluster.name: feathr
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  xpack.security.enabled: "false"
